# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: veterinarysystem
services:
  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - 7742:8080
