package com.veterinary.sistema.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EsteticaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEsteticaAllPropertiesEquals(Estetica expected, Estetica actual) {
        assertEsteticaAutoGeneratedPropertiesEquals(expected, actual);
        assertEsteticaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEsteticaAllUpdatablePropertiesEquals(Estetica expected, Estetica actual) {
        assertEsteticaUpdatableFieldsEquals(expected, actual);
        assertEsteticaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEsteticaAutoGeneratedPropertiesEquals(Estetica expected, Estetica actual) {
        assertThat(expected)
            .as("Verify Estetica auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEsteticaUpdatableFieldsEquals(Estetica expected, Estetica actual) {
        assertThat(expected)
            .as("Verify Estetica relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getDirecion()).as("check direcion").isEqualTo(actual.getDirecion()))
            .satisfies(e -> assertThat(e.getTelefono()).as("check telefono").isEqualTo(actual.getTelefono()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEsteticaUpdatableRelationshipsEquals(Estetica expected, Estetica actual) {}
}
