package com.veterinary.sistema.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RazaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRazaAllPropertiesEquals(Raza expected, Raza actual) {
        assertRazaAutoGeneratedPropertiesEquals(expected, actual);
        assertRazaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRazaAllUpdatablePropertiesEquals(Raza expected, Raza actual) {
        assertRazaUpdatableFieldsEquals(expected, actual);
        assertRazaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRazaAutoGeneratedPropertiesEquals(Raza expected, Raza actual) {
        assertThat(expected)
            .as("Verify Raza auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRazaUpdatableFieldsEquals(Raza expected, Raza actual) {
        assertThat(expected)
            .as("Verify Raza relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getNombreCientifico()).as("check nombreCientifico").isEqualTo(actual.getNombreCientifico()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRazaUpdatableRelationshipsEquals(Raza expected, Raza actual) {
        assertThat(expected)
            .as("Verify Raza relationships")
            .satisfies(e -> assertThat(e.getEnfermedads()).as("check enfermedads").isEqualTo(actual.getEnfermedads()));
    }
}
