package com.veterinary.sistema.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TerapiaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTerapiaAllPropertiesEquals(Terapia expected, Terapia actual) {
        assertTerapiaAutoGeneratedPropertiesEquals(expected, actual);
        assertTerapiaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTerapiaAllUpdatablePropertiesEquals(Terapia expected, Terapia actual) {
        assertTerapiaUpdatableFieldsEquals(expected, actual);
        assertTerapiaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTerapiaAutoGeneratedPropertiesEquals(Terapia expected, Terapia actual) {
        assertThat(expected)
            .as("Verify Terapia auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTerapiaUpdatableFieldsEquals(Terapia expected, Terapia actual) {
        assertThat(expected)
            .as("Verify Terapia relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTerapiaUpdatableRelationshipsEquals(Terapia expected, Terapia actual) {
        assertThat(expected)
            .as("Verify Terapia relationships")
            .satisfies(e -> assertThat(e.getEnfermedads()).as("check enfermedads").isEqualTo(actual.getEnfermedads()));
    }
}
