package com.veterinary.sistema.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TratamientoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoAllPropertiesEquals(Tratamiento expected, Tratamiento actual) {
        assertTratamientoAutoGeneratedPropertiesEquals(expected, actual);
        assertTratamientoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoAllUpdatablePropertiesEquals(Tratamiento expected, Tratamiento actual) {
        assertTratamientoUpdatableFieldsEquals(expected, actual);
        assertTratamientoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoAutoGeneratedPropertiesEquals(Tratamiento expected, Tratamiento actual) {
        assertThat(expected)
            .as("Verify Tratamiento auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoUpdatableFieldsEquals(Tratamiento expected, Tratamiento actual) {
        assertThat(expected)
            .as("Verify Tratamiento relevant properties")
            .satisfies(e -> assertThat(e.getFechaInicio()).as("check fechaInicio").isEqualTo(actual.getFechaInicio()))
            .satisfies(e -> assertThat(e.getFechaFin()).as("check fechaFin").isEqualTo(actual.getFechaFin()))
            .satisfies(e -> assertThat(e.getNotas()).as("check notas").isEqualTo(actual.getNotas()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoUpdatableRelationshipsEquals(Tratamiento expected, Tratamiento actual) {
        assertThat(expected)
            .as("Verify Tratamiento relationships")
            .satisfies(e -> assertThat(e.getHistorial()).as("check historial").isEqualTo(actual.getHistorial()));
    }
}
