package com.veterinary.sistema.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VeterinarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVeterinarioAllPropertiesEquals(Veterinario expected, Veterinario actual) {
        assertVeterinarioAutoGeneratedPropertiesEquals(expected, actual);
        assertVeterinarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVeterinarioAllUpdatablePropertiesEquals(Veterinario expected, Veterinario actual) {
        assertVeterinarioUpdatableFieldsEquals(expected, actual);
        assertVeterinarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVeterinarioAutoGeneratedPropertiesEquals(Veterinario expected, Veterinario actual) {
        assertThat(expected)
            .as("Verify Veterinario auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVeterinarioUpdatableFieldsEquals(Veterinario expected, Veterinario actual) {
        assertThat(expected)
            .as("Verify Veterinario relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getApellido()).as("check apellido").isEqualTo(actual.getApellido()))
            .satisfies(e -> assertThat(e.getDireccion()).as("check direccion").isEqualTo(actual.getDireccion()))
            .satisfies(e -> assertThat(e.getTelefono()).as("check telefono").isEqualTo(actual.getTelefono()))
            .satisfies(e -> assertThat(e.getEspecilidad()).as("check especilidad").isEqualTo(actual.getEspecilidad()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVeterinarioUpdatableRelationshipsEquals(Veterinario expected, Veterinario actual) {
        assertThat(expected)
            .as("Verify Veterinario relationships")
            .satisfies(e -> assertThat(e.getEstudios()).as("check estudios").isEqualTo(actual.getEstudios()));
    }
}
